FROM almalinux:8.10
WORKDIR /build


# Install tools
RUN yum -y install gcc gcc-c++ gcc-gfortran binutils libtool autoconf automake perl curl wget python3 python3-pip git cmake jq tcsh time unzip which patch
RUN wget https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip && unzip ninja-linux.zip && mv ninja /bin

# Prepare source-build files
RUN mkdir -p /install_dir/{netcdf,mpich,hdf5} /install_dir/netcdf/plugin_dir \
    && git clone https://github.com/Unidata/netcdf-c.git \
    && git clone https://github.com/Unidata/netcdf-fortran.git \
    && git clone --recursive https://github.com/pmodels/mpich.git \
    && git clone --recursive https://github.com/wrf-model/WRF.git \
    && git clone --recursive https://github.com/wrf-model/WPS.git \
    && git clone https://github.com/HDFGroup/hdf5.git \
    && mkdir /build/netcdf-fortran/build /build/netcdf-c/build /build/hdf5/build
COPY conanfile-netcdf.txt /build/netcdf-c/conanfile.txt
COPY conanfile-netcdf.txt /build/netcdf-fortran/conanfile.txt
COPY conanfile-wps.txt /build/WPS/conanfile.txt
COPY conanfile-hdf5.txt /build/hdf5/conanfile.txt


# Prepare dependencies conan
ENV PATH="/root/.local/bin:$PATH"
RUN pip3 install conan \
    && conan profile detect \
    && cd /build/netcdf-c \
    && conan install . --build missing --output-folder=build -s build_type=Release \
    && cd /build/netcdf-fortran \
    && conan install . --build missing --output-folder=build -s build_type=Release \
    && cd /build/hdf5 \
    && conan install . --build missing --output-folder=build -s build_type=Release \
    && cd /build/WPS \
    && conan install . --build missing --format json > conaninfo.json


# Build MPICH
ARG mpich_version=v4.2.3rc1
RUN cd /build/mpich \
    && git checkout $mpich_version \
    && ./autogen.sh \
    && ./configure --prefix=/install_dir/mpich \
    && make -j$(nproc) \
    && make install


# Build HDF5
ARG hdf5_version=hdf5_1.14.4.3
COPY hdf5-cmake.patch /build/hdf5/hdf5-cmake.patch
RUN cd /build/hdf5 \
    && git checkout $hdf5_version \
    && git apply hdf5-cmake.patch \
    && cd build \
    && cmake .. -G Ninja --preset conan-release \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/install_dir/hdf5 \
        -DBUILD_STATIC_LIBS=ON \
        -DBUILD_SHARED_LIBS=OFF \
        -DHDF5_BUILD_CPP_LIB=ON \
        -DHDF5_BUILD_FORTRAN=ON \
        -DHDF5_ENABLE_SZIP_SUPPORTL=ON \
        -DHDF5_ENABLE_PARALLEL=OFF \
    && cmake --build . \
    && cmake --install .


# Build NetCDF-C
ARG netcdf_c_version=v4.9.3-rc1
COPY netcdf-c-cmake.patch /build/netcdf-c/netcdf-c-cmake.patch
RUN cd /build/netcdf-c \
    && git checkout $netcdf_c_version \
    && git apply netcdf-c-cmake.patch \
    && cd build \
    && cmake .. -G Ninja --preset conan-release \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH=/install_dir/hdf5/cmake \
        -DCMAKE_INSTALL_PREFIX=/install_dir/netcdf \
        -DNETCDF_PLUGIN_INSTALL_DIR=/install_dir/netcdf/plugin_dir \
        -DBUILD_SHARED_LIBS=OFF \
    && cmake --build . \
    && cmake --install .


# Build NetCDF-Fortran
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
ARG netcdf_fortran_version=v4.6.1
COPY netcdf-fortran-cmake.patch /build/netcdf-fortran/netcdf-fortran-cmake.patch
RUN cd /build/netcdf-fortran \
    && git checkout $netcdf_fortran_version \
    && git apply netcdf-fortran-cmake.patch \
    && cd build \
    && cmake .. -G Ninja --preset conan-release \
        "-DCMAKE_PREFIX_PATH=/install_dir/netcdf/lib/cmake/netCDF;/install_dir/hdf5/cmake" \
        -DCMAKE_INSTALL_PREFIX=/install_dir/netcdf \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=OFF \
    && cmake --build . \
    && cmake --install .


# Build WRF
ENV PATH="/install_dir/mpich/bin:/install_dir/netcdf/bin:$PATH"
ARG wrf_version=v4.6.0
ARG wrf_config_1=34
ARG wrf_config_2=1
ARG wrf_type=em_real
COPY wrf.patch /build/WRF/wrf.patch
RUN cd /build/WRF \
    && source /build/WPS/conanautotoolsdeps.sh \
    && export JASPER=$(cat /build/WPS/conaninfo.json | jq -r '.graph.nodes | [.[] | select(.name == "jasper")] | first | .package_folder') \
    && export HDF5=/install_dir/hdf5 \
    && export NETCDF=/install_dir/netcdf \
    && export LDFLAGS="-L$HDF5/lib $LDFLAGS" LIBS="-lhdf5_hl -lhdf5_fortran -lhdf5_tools -lhdf5 $LIBS" \
    && git checkout $wrf_version \
    && git apply wrf.patch \
    && { echo $wrf_config_1; echo $wrf_config_2; } | ./configure \
    && ./compile $wrf_type \
    && source /build/WPS/deactivate_conanautotoolsdeps.sh \
    && test -f run/wrf.exe


# Build WPS
ARG wps_version=v4.6.0
ARG wps_config=3
COPY wps-almalinux.patch /build/WPS/wps.patch
RUN cd /build/WPS \
    && source /build/WPS/conanautotoolsdeps.sh \
    && export JASPER=$(cat conaninfo.json | jq -r '.graph.nodes | [.[] | select(.name == "jasper")] | first | .package_folder') \
    && export PNG=$(cat conaninfo.json | jq -r '.graph.nodes | [.[] | select(.name == "libpng")] | first | .package_folder') \
    && export ZLIB=$(cat conaninfo.json | jq -r '.graph.nodes | [.[] | select(.name == "zlib")] | first | .package_folder') \
    && export JPEG=$(cat conaninfo.json | jq -r '.graph.nodes | [.[] | select(.name == "libjpeg")] | first | .package_folder') \
    && export HDF5=/install_dir/hdf5 \
    && export NETCDF=/install_dir/netcdf JASPERLIB="$JASPER/lib" JASPERINC="$JASPER/include" \
    && export LDFLAGS2="-L$HDF5/lib -L$ZLIB/lib $LDFLAGS" LIBS2="-lhdf5_hl -lhdf5_fortran -lhdf5_tools -lhdf5 -lz $LIBS" \
    && git checkout $wps_version \
    && git apply wps.patch \
    && echo $wps_config | ./configure \
    && ./compile \
    && source /build/WPS/deactivate_conanautotoolsdeps.sh \
    && test -f ungrib/ungrib.exe
